apiVersion: kinda.rocks/v1
kind: DbInstance
metadata:
  labels:
    app.kubernetes.io/name: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbinstance-sample
spec:
  # TODO(user): Add fields here
