apiVersion: kinda.rocks/v1beta1
kind: DbRestore
metadata:
  labels:
    app.kubernetes.io/name: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbrestore-sample
spec:
  # TODO(user): Add fields here
